name: Deploy to Live Channel

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "public/**"

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          args: deploy --only hosting
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_COUNTING_1A02E }}"
          projectId: counting-1a02e
          channelId: live