name: Deploy to Preview Channel

on:
  workflow_dispatch:

  pull_request:
    paths:
    - "public/**"

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          args: deploy --only hosting
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_COUNTING_1A02E }}"
          expires: 30d
          projectId: counting-1a02e
