name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: 'npm ci && npm run build:ci'
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          args: deploy --only hosting
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_COUNTING_1A02E }}'
          projectId: counting-1a02e
          channelId: live
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
