name: Deploy to Firebase Hosting on PR
on:
  pull_request:
    branches: [ main ]
    paths:
      - public/**

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          args: deploy --only hosting
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_COUNTING_1A02E }}'
          projectId: counting-1a02e
          expiration: 1h
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
